apiVersion: v1
kind: Service
metadata:
  name: karsajobs-back
  labels: 
    app: karsajobs-back
    # tier: backend
spec:
  selector:
    app: karsajobs-back
    # tier: backend
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30102