apiVersion: apps/v1
kind: Deployment
metadata:
  name:  karsajobs-back
  # labels:
  #   app:  karsajobs-back
  #   # tier: backend
spec:
  selector:
    matchLabels:
      app: karsajobs-back
      # tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app:  karsajobs-back
        # tier: backend
    spec:
      containers:
      - name:  karsajobs-back
        image:  ronalyulyanto/karsajobs:latest
        # resources:
        #   requests:
        #     memory: "128Mi" # 128Mi = 128 mebibytes
        #     cpu: "500m"     # 500m = 500 milliCPUs (1/2 CPU)
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m" 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8080
         
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: db-karsajobs
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: db-karsajobs-secret
              key: MONGO_ROOT_USERNAME
        - name : MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: db-karsajobs-secret
              key: MONGO_ROOT_PASSWORD
