apiVersion: v1
kind: Secret
metadata:
  name: db-karsajobs-secret
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==