apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-karsajobs
  
  
spec:
  selector:
    matchLabels:
      app: db-karsajobs
       # has to match .spec.template.metadata.labels
  serviceName: db-karsajobs
  replicas: 1 # by default is 1
  # minReadySeconds: 10
  template:
    metadata:
      labels:
        app: db-karsajobs
         # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
      
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: persistvol-db-karsajobs
          mountPath: /data/db
        - name: config-vol-db-karsajob
          mountPath: /config
        - name: secret-vol-db-karsajob
          mountPath: /etc/mongo-credentials
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME_FILE 
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
      volumes:               
      - name: persistvol-db-karsajobs
        persistentVolumeClaim:
          claimName: pvc-db-karsajobs
      - name: config-vol-db-karsajob
        configMap:
          name: db-config-karsajobs 
          items: 
          - key: mongo.conf
            path: mongo.conf
      - name: secret-vol-db-karsajob
        secret:
          secretName: db-karsajobs-secret